default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'password' %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: myapp_development
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: mycafe_prod
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'password!' %>
  host: <%= ENV['DATABASE_HOST'] %>
