name: Build and Upload Docker Image to S3

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up environment variables
        run: |
          echo "RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}" >> $GITHUB_ENV
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker-compose build
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

      - name: Save Docker image as tar file
        run: docker save johnparkdev23/mycafe:latest -o image.tar

      - name: Upload to S3
        run: aws s3 cp image.tar ${{ secrets.AWS_BUCKET_PATH }}/image.tar --region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Trigger Deploy Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: ${{ github.repository }}
          event-type: trigger-deploy